#!/bin/sh
# Re-download the self-hosted webfonts (Fraunces + Inter) and regenerate
# web/src/fonts.css.
#
# They are self-hosted rather than loaded from Google because the CSP is 'self'
# only, because a wall tablet should render correctly without internet, and
# because a household hub that pings a third party on every page load
# contradicts the rest of this design.
#
# Only needed if you change which weights the UI uses.
set -eu
cd "$(dirname "$0")/.."
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
URL="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..700&family=Inter:wght@400..700&display=swap"

mkdir -p web/public/fonts
tmp=$(mktemp)
curl -sf -A "$UA" "$URL" -o "$tmp"

grep -oE "https://fonts.gstatic.com/[^)]+\.woff2" "$tmp" | sort -u | while read -r url; do
  name="${url##*/}"
  case "$url" in *[Ff]raunces*) fam=fraunces ;; *) fam=inter ;; esac
  curl -sf -A "$UA" "$url" -o "web/public/fonts/${fam}-${name}"
done

{
  printf '/* fonts.css — generated by scripts/fetch-fonts.sh. Do not edit by hand.\n'
  printf ' *\n'
  printf ' * URLs are "../fonts/" because the built stylesheet lands in assets/ --\n'
  printf ' * which also makes them correct behind a path prefix such as /beta/.\n'
  printf ' */\n\n'
  sed -E "s#url\\(https://fonts\\.gstatic\\.com/[^)]*/([^)/]+\\.woff2)\\)#url('../fonts/PLACEHOLDER\\1')#g" "$tmp"
} > web/src/fonts.css

# Restore the family prefix each file was saved under.
sed -i "s#../fonts/PLACEHOLDER#../fonts/#g" web/src/fonts.css
python3 - <<'PY'
import re, os
css = open('web/src/fonts.css').read()
files = os.listdir('web/public/fonts')
def fix(m):
    base = m.group(1)
    for f in files:
        if f.endswith(base):
            return f"url('../fonts/{f}')"
    return m.group(0)
open('web/src/fonts.css','w').write(re.sub(r"url\('\.\./fonts/([^']+\.woff2)'\)", fix, css))
PY
rm -f "$tmp"
echo "fonts refreshed: $(ls web/public/fonts | wc -l) files"
